chore: configurando o lighthouse CI

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,7 +30,17 @@ jobs:
         run: |
           echo "Waiting for deployment to finish..."
           preview_url=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}&limit=1" | jq -r ".deployments[0].url")
-          while [[ $(curl -sL -w "%{http_code}\\\\n" "${preview_url}" -o /dev/null) != "200" ]]; do sleep 10; done
+
+          if [ -z "$preview_url" ]; then
+            echo "Error: No preview URL found. Exiting."
+            exit 1
+          fi
+
+          echo "Preview URL: $preview_url"
+          while [[ ! $(curl -sL -o /dev/null -w "%{http_code}" "${preview_url}") =~ ^(200|301|302)$ ]]; do
+              sleep 10
+          done
+
           echo "Deployment finished. Preview URL: $preview_url"
           echo "PREVIEW_URL=$preview_url" >> $GITHUB_ENV
 
